NVOMS-3147- Tarea adicional para mejor auditoría - Amarrar la Task ID Oms con la Task de Celery
Omnipro-Solutions/saas-app-oms pull request #102
Opened 2024-12-20 20:41 UTC by omniDanna

# NVOMS-3147- Tarea adicional para mejor auditoría - Amarrar la Task ID Oms con la Task de Celery

## ref NVOMS-3147 https://omnipro.atlassian.net/browse/NVOMS-3147

## Descripción
- Este PR agrega el campo celery_tas_id en el modelo Task de la libreria oms.

## Cambios
- Añadido el campo celery_tas_id de tipo string para asociar el id de la tarea en celery.
- Añadido logica para asociar el task oms al celery_result.

## Motivación y contexto
Estos cambios son necesarios para mejorar la auditoria en las tareas.

## Cómo se ha probado
-  Se realizaron pruebas compilando la nueva versión de la librería.

## Screenshots (si aplica)
N/A

## Tipo de cambio
- [x  Bug fix (cambios que solucionan un problema)
- [x] Nueva característica (cambios que añaden funcionalidad)
- [ ] Cambios de breaks (cambio que requiere una modificación en el código existente o en la configuración)
- [ ] Mejoras de rendimiento
- [ ] Otro (especificar)

## Checklist:
- [x] Mi código sigue las directrices de estilo de este proyecto
- [x] He realizado una auto-revisión de mi propio código
- [x] He comentado mi código, especialmente en áreas difíciles de entender
- [x] He hecho cambios correspondientes en la documentación
- [x] Mis cambios no generan nuevas advertencias
- [x] He añadido pruebas que demuestran que mi arreglo es efectivo o que mi característica funciona
- [x] Los cambios necesarios han sido confirmados como efectivos y deseados en pruebas
- [x] Debería ser revisado por al menos un desarrollador más antes de fusionarse

## Notas adicionales
N/A

2024-12-20 21:19 UTC, edgarpena14 requested changes

2024-12-20 21:19 UTC, edgarpena14 commented on omni_pro_oms/admin/task_result.py
> +                print(f"task_args crudo: {repr(obj.task_args)}")
@omniDanna Remover el print

2024-12-20 21:19 UTC, edgarpena14 commented on omni_pro_oms/admin/task_result.py
> +                    return format_html('<a href="{}" target="_blank">Ver Task</a>', url)
@omniDanna validar con varios casos de uso para los parámetros

```shell
>>> task_args = '"(13837,True,14)"'
>>> task_args = task_args.strip('"')
>>> task_args
'(13837,True,14)'
>>> task_args = task_args.replace("(", "").replace(")", "").replace(",", "").strip()
>>> task_args
'13837True14'
>>> task_args = "".join(task_args.split())
>>> task_args
'13837True14'
>>> task_args.isdigit()
False
```

Para el ejemplo anterior '"(13837,True,14)"' el id del primer parámetro si cumple pero al final sale "No disponible"

2025-02-03 21:48 UTC, OmniJulian approved these changes

2025-02-04 16:04 UTC, merged